### ISSUE TITLE
How to install  Akira in linux?

### ISSUE THREAD

**Issue by smEunus** [Alecaddd/akira#1]

**Comment by Alecaddd** [comment]
Thanks for your interested in Akira.
The App is still in super pre-alpha, there's pretty much nothing to see other than an empty layout and a bunch of gibberish C++ classes.

When the alpha will be ready for tests, I will write a documentation on how to install and compile Akira on Linux.

Cheers,

**Comment by smEunus** [comment]
Glad to have your reply. I saw an image editor in your video series 'WordPress Mega Menu from Scratch'. I thought that was may be Akira.
