### ISSUE TITLE
How can I pay you money and encourage my friends to also do so?

### ISSUE THREAD

**Issue by sdaitzman** [Alecaddd/Akira#19]
I am so grateful that you are working on this! I would also love to contribute to the software.

**Comment by Alecaddd** [comment]
Hi @sdaitzman, thank you so much for your interest in Akira!
I have an active Patreon page where you can support me with a small monthly donation of your choice.
Supporting the development of Akira and sharing it with your friends would be amazing, thank you so much!

[Alecaddd Patreon](https://www.patreon.com/alecaddd)
