### ISSUE TITLE
Switch to meson

### ISSUE THREAD

**Issue by benwaffle** [Alecaddd/Akira#24]
Many GNOME and elementary projects are switching to the [meson](http://mesonbuild.com/) build system. It's very fast and has good GTK+ and Vala support. Would you accept a PR for this?

**Comment by Alecaddd** [comment]
Absolutely, I'd love that. Thank you so much 😃

**Comment by Alecaddd** [comment]
Absolutely, I'd love that. Thank you so much 😃
