### ISSUE TITLE
AppImage Problem

### ISSUE THREAD

**Issue by raniaamina** [Alecaddd/Akira#25]
Hi @Alecaddd,
I have download the AppImage of Akira, but unfortunately it can't runt correctly in my Debian Stretch.
Here the error message

```bash
sherlock@reichenbach:~/Programs/Akira$ ./Akira-d74196b-x86_64.AppImage 
akira: symbol lookup error: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: hb_buffer_set_cluster_level
```
What should i do?

In the other hand, i try compile Akira from source. I installed all depencies are needed, but here the result

![area kerja 1_051](https://user-images.githubusercontent.com/22146607/35269035-6ae610ca-005d-11e8-9662-c35a787583ca.png)

There are no menu on top, left, and right.
Hope you can fix this problem :-)

Thank you very much.

**Comment by Alecaddd** [comment]
I'm still trying to properly compile the Appimage, so far it keeps getting outdated libraries and I've no idea why.

If you build from source, the master branch is not updated, I'm working on the `headerbar` branch and you can compile from that if you want to see the current progress.

Still, this is in early pre-alpha, so nothing works really and UI glitches are expected

**Comment by raniaamina** [comment]
Okay, i'll try. 
Thank you for your response :-)
