### ISSUE TITLE
Travis build

### ISSUE THREAD

**Issue by mdh34** [Alecaddd/Akira#28]
Would it be a good idea to add Travis CI to the to the repository to keep track of builds / pull requests etc?

**Comment by Alecaddd** [comment]
Definitely a good idea!
I haven't done that yet because I'm testing the build of an Appimage in another branch via Travis CI, and also because the app is still in pre-alpha with pretty much anything else in it other than the basic layout and header bar.

**Comment by aleksandar-stefanovic** [comment]
Is this issue resolved, now that Houston CI is activated in the project?

**Comment by Alecaddd** [comment]
The build is failing for now, I'll fix it tomorrow and then close this issue if everything goes smoothly.
Thanks for checking 😄
