### ISSUE TITLE
Can't find on AppCenter

### ISSUE THREAD

**Issue by isneezy** [Alecaddd/Akira#34]
Hi, I'm interested in using this promising software.
I'm in elementary OS 0.4.1 (Lock), I clicked the Get it on AppCenter button, but this does not appear in appCenter results, even searching by name.

Is there is anything i can do to help??
This is the kind of software that we, Linux users have been waiting for so long and I'm willing to pay and contribute to their success!
Thanks.

**Comment by Alecaddd** [comment]
Hi, thanks for your interest in Akira.
Unfortunately, it's still in early development, so it's no available in the AppCenter yet.
I should probably remove that button from the readme file, as it could be misleading.
Cheers
