### ISSUE TITLE
the post install script does not honor the prefix

### ISSUE THREAD

**Issue by eyelash** [Alecaddd/Akira#36]
The [post install script](https://github.com/Alecaddd/Akira/blob/master/meson/post_install.py) contains hard-coded paths that assume the prefix is `/usr`. This breaks the build if the prefix is not `/usr`.

**Comment by Alecaddd** [comment]
That should be compatible with every debian based distro.
Where are you trying to compile it?
Cheers

**Comment by eyelash** [comment]
I'm trying to build a flatpak where the prefix is `/app`.

**Comment by Alecaddd** [comment]
Oh, I'm sorry but I've no idea how flatpak works.
For now, I'm focusing only on making it work on elementary os and probably Pop!_OS, considering it comes with the same libs necessary.
The app is still in the early stages of development and it's not usable at all.
Probably, in the future, after a fairly stable beta gets version gets released, I'll look into packaging it for other distro/systems.

Cheers
