### ISSUE TITLE
HOLY CRAP ! A linux app for UI design ! 

### ISSUE THREAD

**Issue by theotix** [Alecaddd/Akira#4]
Daaamn, I just read the readme, I was waiting for this kind of app for so long. You made my day ! ❤️❤️❤️
Maybe it's a bit to soon to see how good this software will be great but I have good hope.

Thank's again, I will follow his development closely !

**Comment by jtrees** [comment]
I was thinking the same thing. Seriously, this thing could be a game changer for linux adoption.

**Comment by Alecaddd** [comment]
Thank you so much, guys! 
I've been prototyping this app for the past 6 months, studying Vala and Gtk, researching current professional tools, and writing a roadmap for the project.
I literally just started yesterday, and the road will be long and not easy just to release a decent alpha version, but I'll try my best to make it happen.
Thanks for your positive feedback.
Linux deserves this!
