### ISSUE TITLE
Problem with focus when editing an item

### ISSUE THREAD

**Issue by alainm23** [Alecaddd/Akira#41]
Good work so far, just a query, how do you think to solve the focus problem when editing an element (text, triangle, circle, etc.), when you double-click a Gtk.Entry is activated but it is not in focus to be able to edit , having to press the left mouse button. I say this because I have the same problem in Planner and because of this, stop using Gtk.ListBox for a Gtk.Grid

**Comment by Alecaddd** [comment]
I fixed the issue by adding a delay to the focus grabbing method.
Without the delay, the entry gets the focus and loses it at the same time.

Here's the snippet I used:
```
Timeout.add (200, () => {
				entry.grab_focus ();
				return false;
			});
```
which you can find in this file: https://github.com/Alecaddd/Akira/blob/dev/src/Layouts/Partials/Layer.vala#L357
