### ISSUE TITLE
Difficulties to build the project from sources

### ISSUE THREAD

**Issue by LucileDT** [Alecaddd/Akira#42]
Hi!

I'm sorry, I don't usually develop things which need to be compiled so I'm pretty new to technologies/methods used and I'm not really autonomous to solve my problems.

Your README explains in [Building](https://github.com/Alecaddd/Akira#building) how to build the project but I run into several errors.

... | Configuration
------------ | -------------
OS | Ubuntu 16.04
Meson version | 0.29.0

### Missing `build` folder
The first time I ran `meson build --prefix=/usr`, it gave me an error:
>     luciledt@computer:~/development/Akira$ meson build --prefix=/usr
>     Error during basic setup:
>     
>     [Errno 2] No such file or directory: '/home/lucildt/development/Akira/build'

I needed to create manually the `build` folder so maybe you need to add this to the [Building](https://github.com/Alecaddd/Akira#building) chapter.

### ImportError: No module named 'mesonbuild.modules.i18n'
Then, when I run `meson build --prefix=/usr`, there is a lot of verbose and it ends with an error:
>     luciledt@computer:~/development/Akira$ meson build --prefix=/usr
>     The Meson build system
>     Version: 0.29.0
>     Source dir: /home/luciledt/development/Akira
>     Build dir: /home/luciledt/development/Akira/build
>     Build type: native build
>     Build machine cpu family: x86_64
>     Build machine cpu: x86_64
>     Project name: com.github.alecaddd.akira
>     Native vala compiler: valac (unknown 0.30.1)
>     Native c compiler: cc (gcc 5.4.0-6ubuntu1)
>     Traceback (most recent call last):
>       File "/usr/share/meson/mesonbuild/mesonmain.py", line 250, in run
>          app.generate()
>       File "/usr/share/meson/mesonbuild/mesonmain.py", line 160, in generate
>          intr.run()
>       File "/usr/share/meson/mesonbuild/interpreter.py", line 1028, in run
>          self.evaluate_codeblock(self.ast)
>       File "/usr/share/meson/mesonbuild/interpreter.py", line 1050, in evaluate_codeblock
>          raise e
>       File "/usr/share/meson/mesonbuild/interpreter.py", line 1044, in evaluate_codeblock
>          self.evaluate_statement(cur)
>       File "/usr/share/meson/mesonbuild/interpreter.py", line 1162, in evaluate_statement
>          return self.assignment(cur)
>       File "/usr/share/meson/mesonbuild/interpreter.py", line 1976, in assignment
>          value = self.evaluate_statement(node.value)
>       File "/usr/share/meson/mesonbuild/interpreter.py", line 1160, in evaluate_statement
>          return self.function_call(cur)
>       File "/usr/share/meson/mesonbuild/interpreter.py", line 1957, in function_call
>          return self.funcs[func_name](node, self.flatten(posargs), kwargs)
>       File "/usr/share/meson/mesonbuild/interpreter.py", line 70, in wrapped
>          return f(self, node, args, kwargs)
>       File "/usr/share/meson/mesonbuild/interpreter.py", line 62, in wrapped
>          return f(self, node, args, kwargs)
>       File "/usr/share/meson/mesonbuild/interpreter.py", line 1097, in func_import
>          module = importlib.import_module('mesonbuild.modules.' + modname).initialize()
>       File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
>          return _bootstrap._gcd_import(name[level:], package, level)
>       File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>       File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>       File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
>     ImportError: No module named 'mesonbuild.modules.i18n'

It seems Meson can't get the module you use for translation, as specified in the `meson.build` file but I don't know Meson and I don't know how to solve this. Could you help me?

Thanks!

**Comment by BaptisteGelez** [comment]
I think you should update Meson, the latest version is 0.46 and the i18n module should have been introduced after the 0.29.

**Comment by LucileDT** [comment]
Seems to do the trick (I don't have the error anymore), I'll keep you updated if I manage to build the project!
Maybe it would be necessary to update the README and precise the needed minimal version of Meson :slightly_smiling_face:

**Comment by Alecaddd** [comment]
Closing this as the project is not even close to alpha and it's normal to be pretty broken.
