### ISSUE TITLE
Questions? Ask here!

### ISSUE THREAD

**Issue by surajmandalcell** [Alecaddd/Akira#43]
Is this project still active or is it abandoned?

**Comment by Alecaddd** [comment]
100% active!
I'm learning more about Vala and GTK with my other app, Sequeler.
Akira, is a really complex application and it'll take me a lot to make it, but you can be sure I'll never abandon it!

**Comment by surajmandalcell** [comment]
nice, good to know!
I, ill rename this to general questions so everyone can ask their questions here,
I'm interested in gtk and vala too, but still learning (totally new).

**Comment by e200** [comment]
@surajmandalcell, thanks for this idea.

**Comment by Alecaddd** [comment]
I have a dedicated forum with Akira related topics where you can ask questions and discuss freely.
https://forum.alecaddd.com

Let's keep the GitHub issues just for actual issues and bug reports.

Thanks for your interest in Akira

**Comment by surajmandalcell** [comment]
Why is this forum not linked in readme?

**Comment by Alecaddd** [comment]
That's a good point, I'll add this link ASAP
