### ISSUE TITLE
Icons are inconsistent across themes

### ISSUE THREAD

**Issue by somas95** [Alecaddd/Akira#45]
The icons used are pretty inconsistent with the desktop
![image](https://user-images.githubusercontent.com/8913975/41499102-3fd5251c-717b-11e8-9db3-11b3f56c3bb6.png)

**Comment by Alecaddd** [comment]
Akira is still in early development and has not been released yet.
Also, I'm currently using the system icons as a quick way of building an MVP, and it's normal for those to change based on the theme your distro is using.
