### ISSUE TITLE
Building problem: A required package was not found

### ISSUE THREAD

**Issue by theotix** [Alecaddd/Akira#5]
Hello,
I tried to build Akira on a fresh and up to date install of Elementary and I've been stuck on the `cmake` step:
Every dependencies [listed on the readme](https://github.com/Alecaddd/Akira#install-it-from-source) was found. 
Here the full log, do you have an idea ?
```
theotix@eOS-vm:~/Akira/build$ sudo cmake -DCMAKE_INSTALL_PREFIX=/usr ../
-- Checking for modules 'gtk+-3.0;granite;glib-2.0;gee-0.8;gobject-2.0;libxml-2.0;gtksourceview-3.0'
--   No package 'gtk+-3.0' found
--   No package 'granite' found
--   No package 'glib-2.0' found
--   No package 'gee-0.8' found
--   No package 'gobject-2.0' found
--   No package 'libxml-2.0' found
--   No package 'gtksourceview-3.0' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  CMakeLists.txt:32 (pkg_check_modules)
```

**Comment by julientaq** [comment]
Hey!
looks  like no dependencies been found: 
`--  No package 'granite' found`

look here:
https://askubuntu.com/questions/779065/pkg-config-not-finding-gtk-3-0


i'm not running elementary, but on my arch, app is building, but i end up on a white screen though.

**Comment by Alecaddd** [comment]
Thanks for the passion, guys, but I literally started coding the app yesterday night. It's a non-tested and empty container for now.
A pre alpha release, with something to use in it, should be released before the end of the month.

**Comment by theotix** [comment]
Strange that the dependencies wasn't found, I have manually install them through apt.
However I'll wait for an alpha to report bugs, It's useless at this early state of development.

**Comment by Alecaddd** [comment]
@theotix thank you so much 😃
