### ISSUE TITLE
Is there anyway I can build and try it in Mac?

### ISSUE THREAD

**Issue by manoj-makkuboy** [Alecaddd/Akira#57]
I tried installing dependencies brew doesn't have a lot of them. Any advice on the same will be very useful.

**Comment by nickhq** [comment]
Switch to Linux 😂😂 just kidding. I don't think it's easy

**Comment by Alecaddd** [comment]
No idea, sorry.
Akira is built with Linux and mostly Ubuntu based dependencies.
Closing this issue as it's out of the scope and objective of the project.

**Comment by gusbemacbe** [comment]
The app should remain only for Linux and GPL-licensed.
