### ISSUE TITLE
[Bug] No Response when Running Akira Appimage on Lubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by ditokp** [Alecaddd/Akira#59]
When I double click the Akira Appimage and click execute or execute in the terminal there is no response at all. And then I try open the terminal and change the directory to Akira and execute appimage with this code:
>`./Akira-d74196b-x86_64.AppImage`

I have this error message:
>`./Akira-d74196b-x86_64.AppImage 
>
>akira: symbol lookup error: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: hb_font_funcs_set_variation_glyph_func`

**Comment by Alecaddd** [comment]
The project is still in early alpha and the appimage was just a test to see the building process.
Nothing is working or usable yet.
Thanks for your interest in Akira, a packaged alpha version should be available in few months.
