### ISSUE TITLE
Empty window on startup

### ISSUE THREAD

**Issue by jtrees** [Alecaddd/Akira#6]
When I start the application (f8ca213ff79dc10b1e5c8888b7ed65e00a985db0) I simply get a white window. It seems the path to the linked stylesheet is broken (also note how the path contains "sequeler" instead of "akira").

```
[WARNING 16:48:12.884001] [Gtk] Theme parsing error: <broken file>:1:0: Failed to import: The resource at '/com/github/alecaddd/sequeler/stylesheet.css' does not exist
```

**Comment by Alecaddd** [comment]
Thanks for the heads-up. I'm still setting up the initial files and transitioning what I have from Sequeler.
The app is currently totally empty, I will be able to release a pre alpha before the end of the month.

**Comment by jtrees** [comment]
Alrighty then. Can't wait to see how this progresses.
