### ISSUE TITLE
Kickstarter Campaign Video

### ISSUE THREAD

**Issue by ryantheleach** [Alecaddd/Akira#64]
Your audio is a little messy, slight hiss, Additionally, If you don't meet your goals, and you take another shot, you should show more of your gifs/ui/ux mockups in the video, like you have further down the page.

**Comment by Alecaddd** [comment]
Hi, thanks for the feedback. I know my video is pretty bad and I'm currently creating a new one to replace it and better advertise Akira.
Cheers
