### ISSUE TITLE
Make the drawing canvas it's own library

### ISSUE THREAD

**Issue by Philip-Scott** [Alecaddd/Akira#7]
Hi Alex! 

I'd like to talk to you about maybe working together to make the drawing canvas as it's own independent widget so that it can later be used on other apps such as [Spice-Up](https://github.com/Philip-Scott/Spice-up)

The current version of Spice-Up is using all native widgets (like Labels) and CSS for it's rendering and positioning, which tbh is a bit hackish and is kind of broken in the latest Gtk 3.22 version. It also has it's limitations with things like rotations and custom shapes. So maybe we need to make our own canvas renderer from scratch :)

**Comment by Alecaddd** [comment]
Oh man, I'd love to!
Actuallyone of the features I have in the backlog is a "export to spice up" button, to automatically convert artboards into slides from your app.

Do you wanna have a call one of these days?

**Comment by Philip-Scott** [comment]
Oh that would be sweet! 

For sure, i'l love to chat some day! I'm officially out of school for the semester, so i'm basically free to chat whenever you can :)

**Comment by Alecaddd** [comment]
Are you on the elementary slack?
I can add you to mine if you want

**Comment by Philip-Scott** [comment]
If you could add me to yours that would be great :) Much easier than talking though here or emails

**Comment by esodan** [comment]
Hi all, for sure I'll love to work with others to take advantage of my work on GSVG and create a canvas I'll need for other projects like plogic.

May first issue here is that GSVG and its GTK+ widgets are developed on GitLab:

https://gitlab.com/pwmc/gsvg

https://gitlab.com/pwmc/gsvgtk

**Comment by Alecaddd** [comment]
@esodan oh wow, this looks awesome. Do you have any built app I could compile and run locally to see this library in action?
