### ISSUE TITLE
Forum post linked at the end of the readme is outdated, just letting you know

### ISSUE THREAD

**Issue by surajmandalcell** [Alecaddd/Akira#75]
Forum post mentioned in readme still says akira will be developed in qt whilst its now being written in vala. Just a remainder to update the post.

Kickstarter page : 
![image](https://user-images.githubusercontent.com/11650177/51863809-03de9300-2368-11e9-823d-c7511e7b7114.png)
Forum page :
![image](https://user-images.githubusercontent.com/11650177/51863843-1b1d8080-2368-11e9-9618-85c1b5351d63.png)

Close the issue when you notice this 👍

**Comment by Alecaddd** [comment]
That's an old post written a year ago and it's part of the history and decision making process of Akira.
No need to change the forum post or update the readme file.
